frappe.pages["factory-schedule"].on_page_load = function (wrapper) {
    const page = frappe.ui.make_app_page({parent: wrapper, title: __("Factory Production Schedule"), single_column: true});
    page.main.addClass("factory-schedule-page"); page.set_primary_action(__("Refresh Queue"), () => load_schedule(page)); page.add_inner_button(__("What-if Simulation"), () => open_simulation(page)); load_schedule(page);
};
function load_schedule(page) { frappe.call({method:"wood_factory.wood_factory.page.factory_schedule.factory_schedule.get_production_schedule", freeze:true}).then(r => render_schedule(page, r.message || {})); }
function render_schedule(page, data) {
    const s=data.summary||{}, rows=data.orders||[], bottlenecks=data.bottlenecks||[], recommendations=data.recommendations||[], top=bottlenecks[0];
    page.main.html(`<div class="schedule-kpis">${kpi(__("Queued Orders"),s.queued)}${kpi(__("Urgent"),s.urgent,"urgent")}${kpi(__("At Risk / Late"),s.at_risk,"high")}${kpi(__("Recommendations"),recommendations.length,"warning")}</div>${bottleneck_panel(top,bottlenecks)}${recommendation_panel(recommendations)}<div class="schedule-list">${rows.map(order=>`<button class="schedule-row priority-${(order.priority||"normal").toLowerCase()}" data-order="${order.name}"><strong class="queue-number">#${order.queue_position}</strong><div><b>${order.name}</b><span>${frappe.utils.escape_html(order.customer||"")}</span></div><div><b>${__(order.priority)}</b><span>${order.priority_override?__("Manual override"):__("Automatic priority")}</span></div><div><b>${__(order.current_stage||order.status)}</b><span>${order.workstation?frappe.utils.escape_html(order.workstation):__("Workstation not assigned")}</span></div><div><b>${eta_text(order)}</b><span class="eta-risk-${slug(order.eta_risk)}">${__(order.eta_risk||"No Forecast")}</span></div><div><b>${delivery_text(order)}</b><span>${order.open_exceptions} ${__("open exception(s)")}</span></div></button>`).join("")||`<div class="schedule-empty">${__("No orders waiting for production")}</div>`}</div>`);
    page.main.find("[data-order]").on("click",function(){frappe.set_route("Form","Factory Order",$(this).data("order"));});
    page.main.find(".show-bottlenecks").on("click",()=>show_bottlenecks(bottlenecks));
    page.main.find(".show-recommendations").on("click",()=>show_recommendations(recommendations));
}
function recommendation_panel(rows){if(!rows.length)return `<div class="recommendation-empty">${__("No urgent production recommendations. Current flow is stable.")}</div>`;const top=rows[0];return `<button class="recommendation-panel severity-${slug(top.severity)} show-recommendations"><div><span>${__("Top Production Recommendation")}</span><b>${frappe.utils.escape_html(top.title)}</b><small>${frappe.utils.escape_html(top.details)}</small></div><div><strong>${rows.length}</strong><span>${__("Recommendation(s)")}</span></div><div><span>${__("View action plan")} →</span></div></button>`;}
function show_recommendations(rows){const body=rows.map(x=>`<tr><td>#${x.rank}</td><td><b class="recommendation-${slug(x.severity)}">${__(x.severity)}</b></td><td>${__(x.type)}</td><td>${x.stage?__(x.stage):"-"}</td><td><b>${frappe.utils.escape_html(x.title)}</b><br><span class="text-muted">${frappe.utils.escape_html(x.details||"")}</span></td></tr>`).join("");frappe.msgprint({title:__("Production Recommendations"),wide:true,message:`<table class="table table-bordered"><thead><tr><th>#</th><th>${__("Priority")}</th><th>${__("Action")}</th><th>${__("Stage")}</th><th>${__("Recommendation")}</th></tr></thead><tbody>${body||`<tr><td colspan="5">${__("No recommendations")}</td></tr>`}</tbody></table><p class="text-muted">${__("Recommendations are decision support. Queue or staffing changes require manager approval.")}</p>`});}
function bottleneck_panel(top,rows){if(!top)return "";return `<button class="bottleneck-panel severity-${slug(top.severity)} show-bottlenecks"><div><span>${top.is_current_bottleneck?__("Current Production Bottleneck"):__("Highest Production Load")}</span><b>${__(top.stage)}</b></div><div><strong>${top.load_percent}%</strong><span>${__("Load")}</span></div><div><strong>${top.waiting_orders}</strong><span>${__("Waiting Orders")}</span></div><div><strong>${top.queue_delay_days===null?"∞":top.queue_delay_days}</strong><span>${__("Queue Days")}</span></div><div><strong>${frappe.utils.escape_html(top.primary_workstation||"-")}</strong><span>${__("Highest Loaded Workstation")}</span></div><div><span>${__("View all stages")} →</span></div></button>`;}
function show_bottlenecks(rows){const body=rows.map(x=>`<tr><td>#${x.rank} <b>${__(x.stage)}</b></td><td><b class="bottleneck-${slug(x.severity)}">${__(x.severity)}</b></td><td>${x.load_percent}%</td><td>${x.waiting_orders}</td><td>${x.blocked_orders}</td><td>${x.queue_delay_days===null?"∞":x.queue_delay_days}</td><td>${frappe.utils.escape_html(x.primary_workstation||"-")}</td></tr>`).join("");frappe.msgprint({title:__("Production Bottleneck Analysis"),wide:true,message:`<table class="table table-bordered"><thead><tr><th>${__("Stage")}</th><th>${__("Status")}</th><th>${__("Load")}</th><th>${__("Waiting")}</th><th>${__("Blocked")}</th><th>${__("Queue Days")}</th><th>${__("Highest Loaded Workstation")}</th></tr></thead><tbody>${body||`<tr><td colspan="7">${__("No active production load")}</td></tr>`}</tbody></table>`});}
function open_simulation(page) {
    const dialog=new frappe.ui.Dialog({title:__("What-if Production Simulation"),fields:[{fieldname:"workstation",fieldtype:"Link",options:"Factory Workstation",label:__("Unavailable Workstation")},{fieldname:"downtime_days",fieldtype:"Float",label:__("Downtime Days"),default:0},{fieldname:"urgent_order",fieldtype:"Link",options:"Factory Order",label:__("Expedite Order")},{fieldname:"urgent_minutes",fieldtype:"Float",label:__("Extra Work Minutes"),default:0}],primary_action_label:__("Simulate"),primary_action(values){frappe.call({method:"wood_factory.wood_factory.page.factory_schedule.factory_schedule.simulate_production",args:values,freeze:true}).then(r=>{dialog.hide();show_simulation(r.message||{});});}}); dialog.show();
}
function show_simulation(data){const s=data.summary||{},rows=data.impacts||[];const body=rows.map(x=>`<tr><td>${frappe.utils.escape_html(x.order)}</td><td>${x.shift_hours}h</td><td>${__(x.before_risk)}</td><td><b class="eta-risk-${slug(x.after_risk)}">${__(x.after_risk)}</b></td><td>${x.after_completion?frappe.datetime.str_to_user(x.after_completion):"-"}</td></tr>`).join("");frappe.msgprint({title:__("Simulation Impact"),wide:true,message:`<p><b>${__("Affected Orders")}:</b> ${s.affected||0} · <b>${__("New At Risk / Late")}:</b> ${s.new_at_risk||0} · <b>${__("Late After Scenario")}:</b> ${s.late_after||0} · <b>${__("Maximum Delay")}:</b> ${s.max_shift_hours||0}h</p><table class="table table-bordered"><thead><tr><th>${__("Order")}</th><th>${__("ETA Shift")}</th><th>${__("Before")}</th><th>${__("After")}</th><th>${__("New ETA")}</th></tr></thead><tbody>${body||`<tr><td colspan="5">${__("Scenario causes no forecast change")}</td></tr>`}</tbody></table>`});}
function kpi(label,value,tone=""){return `<div class="schedule-kpi ${tone}"><span>${label}</span><b>${value||0}</b></div>`;}
function delivery_text(order){if(order.computed_delay_days)return `${order.computed_delay_days} ${__("days late")}`;if(order.days_left===null)return __("No delivery date");return order.days_left===0?__("Due today"):`${order.days_left} ${__("days left")}`;}
function eta_text(order){return order.estimated_completion?`${__("ETA")}: ${frappe.datetime.str_to_user(order.estimated_completion)}`:__("ETA unavailable");}
function slug(value){return (value||"").toLowerCase().replaceAll(" ","-");}
